# Generated by Django 5.2.8 on 2025-12-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_brand_product_color_product_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
